# Generated by Django 5.2.8 on 2026-01-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_audio_deleted_at_audio_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='audio/images/'),
        ),
    ]
