# Generated by Django 5.2.8 on 2026-01-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0003_audio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='summarized',
            field=models.BooleanField(default=False),
        ),
    ]
