# Generated by Django 5.2.8 on 2026-01-05 09:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('model_name', models.CharField(blank=True, max_length=50)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='audios.audio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
