# Generated by Django 5.2.8 on 2026-01-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
