# Generated by Django 5.2.8 on 2026-01-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0002_transcription_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
