# Generated by Django 5.2.8 on 2026-01-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
        ),
    ]
