# Generated by Django 5.2.8 on 2026-01-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aisummary_input_tokens_aisummary_output_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisummary',
            name='topics',
            field=models.JSONField(default=list),
        ),
    ]
