# Generated by Django 5.2.8 on 2026-02-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aisummary_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisummary',
            name='action_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aisummary',
            name='notable_quotes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aisummary',
            name='speakers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
